language: cpp
sudo: false

matrix:
  include:

    - os: linux
      compiler: gcc
      env: SOURCES=ubuntu-toolchain-r-test
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
             # compilers
            - g++
            #- gfortran
            - cmake
              # math libraries
           # - libblas-dev
           # - liblapack-dev
           # - libatlas-base-dev
              # python library, development version
            #- libpython2.7
            - python3
            - libpython-all-dev
              # boost
            - libboost-all-dev
            - libopenexr-dev
            - libopenjpeg-dev
            - libtiff5 
            - libtiff5-dev
            - gambas3-gb-openal
            - libghc-openal-dev
            - libjemalloc-dev
            - spacenavd
            - libopenimageio-dev

install:
  - pip install --user virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install pep8 pytest

#
# python3 -c 'import sys; print (sys.path[1])'

script:
   - git clone git://git.blender.org/blender.git
   - cd blender
   - git submodule update --init --recursive
   - git submodule foreach git checkout master
   - git submodule foreach git pull --rebase origin master
   # compile blender in own build subdirectory
   - mkdir build
   - cd build
   - cmake -DPYTHON_LIBRARY=/usr/bin/python3.4m -DPYTHON_INCLUDE_DIR=/usr/include/python3.4m  ..
   - make 

notifications:
  email: false
