language: C++

sudo: enabled

git:
  quiet: true

before_install:
   - sudo add-apt-repository ppa:irie/openimageio -y # https://launchpad.net/ubuntu/+source/openimageio
   - sudo add-apt-repository ppa:irie/openexr -y  # https://launchpad.net/~irie/+archive/ubuntu/openexr
   - sudo apt-get update -qq
   - sudo apt-get install -qq cmake
   - sudo apt-get install -qq python3 libpython-all-dev 
   - sudo apt-get install -qq libboost-all-dev 
   - sudo apt-get install -qq libopenexr-dev 
   - sudo apt-get install -qq libopenjpeg-dev 
   - sudo apt-get install -qq libtiff5 libtiff5-dev
   - sudo apt-get install -qq libghc-openal-dev libjemalloc-dev spacenavd 
# default Trusty's OpenImageIO 1.3 does not work , needs higher version - 1.7 !
   - sudo apt-get install -qq libopenimageio-dev 
   - sudo apt-get install -qq libilmbase-dev

install:
   - echo -e "Clonig BLENDER..."
   - git clone git://git.blender.org/blender.git
   - cd blender
   - git submodule update --init --recursive
   - git submodule foreach git checkout master
   - git submodule foreach git pull --rebase origin master
   # print last 3 commits
   - echo -e "\n Last 3 commits of blender:"
   - git log -3

script:
   - echo -e "\n Ubuntu whereabouts:"
   - lsb_release -a
   - echo -e "\n The shell is $SHELL"
   - let "N_PROC=$(cat /proc/cpuinfo | grep processor | wc -l)"
   - echo -e "\n Number of processors/jobs for the build step is $N_PROC"
   # compile blender in own build subdirectory
   - mkdir build
   - cd build
   - cmake -DPYTHON_LIBRARY=/usr/bin/python3.4m -DPYTHON_INCLUDE_DIR=/usr/include/python3.4m  ..
   - make -j $N_PROC

notifications:
  email: false
