language: cpp

before_install:
  # update apt-gets repository sources
  - sudo apt-get update -qq
  - sudo apt-get install cmake python3 libboost-all-dev libopenjpeg-dev
  - sudo apt-get install libpython-all-dev libopenexr-dev libtiff5-dev libghc-openal-dev 
  - sudo apt-get install libjemalloc-dev spacenavd libopenimageio-dev libilmbase-dev 


install:
  - lsb_release -a
  - let "N_PROC=$(cat /proc/cpuinfo | grep processor | wc -l)"
  - git clone git://git.blender.org/blender.git
  - cd blender
  - git submodule update --init --recursive
  - git submodule foreach git checkout master
  - git submodule foreach git pull --rebase origin master
  - echo -e "\n Last 3 commits of blender:"
  - git log -3

script: 
  - mkdir build
  - cd build
  - cmake -DPYTHON_LIBRARY=/usr/bin/python3.4m -DPYTHON_INCLUDE_DIR=/usr/include/python3.4m  ..
  - make -j $N_PROC

