language: cpp
sudo: false

matrix:
  include:

    - os: linux
      compiler: gcc
      env: SOURCES=ubuntu-toolchain-r-test
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
             # compilers
            - g++
            #- gfortran
            - cmake
              # math libraries
           # - libblas-dev
           # - liblapack-dev
           # - libatlas-base-dev
              # python library, development version
            #- libpython2.7
            - libpython-all-dev
              # boost
            - libboost-all-dev

install:
  - pip install --user virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install pep8 pytest

script:
    # pep8 tests
 # - pep8 --ignore=E501 lib/config.py
    # unit tests
 # - py.test -vv update.py
 # - py.test -vv test/test.py
 # - py.test -vv lib/config.py
   - git clone git://git.blender.org/blender.git
   - cd blender
   - git submodule update --init --recursive
   - git submodule foreach git checkout master
   - git submodule foreach git pull --rebase origin master
   - cd .. # go out
   - mkdir build
   - cmake -DPYTHON_LIBRARY=/usr/bin/python3.4m -DPYTHON_INCLUDE_DIR=/usr/include/python3.4m ../blender
   - make 

notifications:
  email: false
