language: C++
sudo: enabled

before_install:
   - sudo add-apt-repository ppa:irie/openimageio
   - sudo apt-get update -qq
   - sudo apt-get install -qq cmake python3 libpython-all-dev libboost-all-dev 
   - sudo apt-get install -qq libopenexr-dev libopenjpeg-dev libtiff5 libtiff5-dev
   - sudo apt-get install -qq libghc-openal-dev libjemalloc-dev spacenavd libopenimageio-dev
   - sudo apt-get install -qq libilmbase-dev

install:
   - echo -e "Clonig BLENDER..."
   - git clone git://git.blender.org/blender.git
   - cd blender
   - git submodule update --init --recursive
   - git submodule foreach git checkout master
   - git submodule foreach git pull --rebase origin master
   # print last 3 commits
   - echo -e "\n Last 3 commits of blender:"
   - git log -3

script:
   - echo -e "\n Ubuntu whereabouts: \n"
   - lsb_release -a
   - echo "The shell is $SHELL"
   - let "N_PROC=$(cat /proc/cpuinfo | grep processor | wc -l)"
   - echo "Number of processors/jobs for the build step is $N_PROC"
   # compile blender in own build subdirectory
   - mkdir build
   - cd build
   - cmake -DPYTHON_LIBRARY=/usr/bin/python3.4m -DPYTHON_INCLUDE_DIR=/usr/include/python3.4m  ..
   - make -j $N_PROC

notifications:
  email: false
